### ISSUE TITLE
Question about the evaluation

### ISSUE THREAD

**Issue by Van5SE** [qq456cvb/CPPF#5]
Dear Author,
        We noticed that you changed your evaluation code from NOCS because the original way to calculate 3D IoU is buggy.
        However I am wondering that why did you chang all your evaluation codes rather than just replace the function and keep other evaluation code:
```python
def asymmetric_3d_iou(RT_1, RT_2, size_1, size_2):
```
      
In my experiments, your model could report this metrics in your evaluation, which is the same as the result reported in your paper

mAP 25 | mAP 50 | mAP 75 | 10cm | 10° | 10° 10cm | 5° 5cm | 10° 5cm
-- | -- | -- | -- | -- | -- | -- | --
78.5 | 26 | 0.1 | 99.9 | 48.7 | 48.2 | 17.4 | 17.7

but report this result when simply repalce the asymmetric_3d_iou

mAP 25 | mAP 50 | mAP 75 | 10cm | 10° | 10° 10cm | 5° 5cm | 10° 5cm
-- | -- | -- | -- | -- | -- | -- | --
82.9 | 72.3 | 10.3 | 98.1 | 47 | 46.2 | 16.5 | 44.4

Could your explain why did you chang your evaluation code in this way? Thanks a lot!

**Comment by qq456cvb** [comment]
Hi, @Van5SE , thanks for asking and this is a good question that I would like to clarify.

Notice that in https://github.com/qq456cvb/CPPF/blob/main/utils/util.py#L764 and https://github.com/qq456cvb/CPPF/blob/main/utils/util.py#L754, we are denormalizing both RTs and scales.
Original NOCS assumes that `gt_RTs` and `pred_RTs` are all multiplied by the norm of the scale, and the `scales` would have a unit length if you print it. This step seems to be counter-intuitive, and we reverse it for code readability.
Now the `scales` are the actual real-world sizes of the bounding box and the determinant of rotation part of `gt_RTs` and `pred_RTs` would be 1, meaning they are proper rotation matrixes.

Return to the question, if you simply replace `asymmetric_3d_iou` without denormalizing rotation and scale, you will not get the correct IoU since we are assuming a real-world size and proper rotation (not really for rotation because we reverse the rotation scale on https://github.com/qq456cvb/CPPF/blob/main/utils/util.py#L188, but `scales` are not reversed to the real-world size, our bad anyway). To correct this, you can either reverse the real-world `scales`, e.g., `scales *= np.cbrt(np.linalg.det(RT_1[:3, :3])`, or denormalize RTs and scales in the first place like we do.

Hope this clarifies the concern. Feel free to ask if you have any questions.

**Comment by Van5SE** [comment]
Dear Author @qq456cvb ,
Very appreciate for your replay！ I will futher understand the code based on your explanation .

Other than above, I got another question. What is your understanding of the original NOCS code on calculating 3D IoU is buggy？ I think the NOCS author might forget to add a tranpose after **_transform_coordinates_3d_** 
  https://github.com/hughw19/NOCS_CVPR2019/blob/14dbce775c3c7c45bb7b19269bd53d68efb8f73f/utils.py#L249 , which lead to an unreasonable 3D IoU results. 
If we add a transpose we can make the results more resonable， which is the same as https://github.com/OasisYang/Wild6D/blob/main/lib/utils.py#L283 . 
I was wondering whether the original code made any physical meaning or not？

Thank you very much!

**Comment by qq456cvb** [comment]
Not really, the original code is calculating IoU between volumes made by bounding box corners. However, **transform_coordinates_3d** applies the rotation to the bounding box, making it skewed, meaning that the bounding box volume cannot be simply calculated by the product of (max - min) xyz coordinates. Therefore, this piece of code is correct only if the bounding box happens to be axis-aligned after the rotation.

**Comment by Van5SE** [comment]
So do you mean that neither origin nor transpose performs well in reality. Ojbectron is the best one to solve this problem?

**Comment by qq456cvb** [comment]
Actually, we are not solving any problem or compare methods. All we need is an accurate metric that reflect the performance of different methods. We borrow the evaluation code from Objectron without using its method.

**Comment by Van5SE** [comment]
I get it . Thank you very much for your kindly patience.
Best wishes!
