### ISSUE TITLE
The missing checkpoints

### ISSUE THREAD

**Issue by Van5SE** [qq456cvb/CPPF#6]
Dear author,
       We found that the checkpoints of classes: **'toilet':4, 'desk':5, 'dresser':6, 'night_stand':7** in SUNRGBD dataset  were not provided. Could you please provide those checkpoints on Google Drive? Thanks a lot!

**Comment by qq456cvb** [comment]
Hi, we did not train on these classes since ShapeNetCore-55 does not come with the corresponding object models. But if you are interested, you can train our zero-shot network on e.g., [Objectron dataset](https://objaverse.allenai.org/), which I think you can find some 3D models of these four categories.
